server:
  port: 8888

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka

logstash:
  host: localhost:5030

spring:
  application:
    name: apizza-gateway

  kafka:
    bootstrap-servers: localhost:29092

  cloud:
    gateway:
      routes:
        - id: apizza.auth
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
          filters:
            - RewritePath=/auth/?(?<segment>.*), /$\{segment}
        - id: apizza.order
          uri: lb://apizza-order
          predicates:
            - Path=/order/**
          filters:
            - RewritePath=/order/?(?<segment>.*), /$\{segment}