server:
  port: 8088

eureka:
  client:
    enabled: false

logstash:
  host: localhost:5030

spring:
  application:
    name: apizza-gateway

  kafka:
    bootstrap-servers: localhost:29092

  cloud:
    gateway:
#      mvc:
        routes:
          - id:
              apizza-authService
            uri:
              lb://apizza-authService
            predicates:
              - Path=/apizza-authService/**
          - id:
              apizza-orderService
            uri:
              lb://apizza-orderService
            predicates:
              - Path=/apizza-orderService/**
            filters:
              - TokenRelay=
              - RemoveRequestHeader=Cookie
          - id:
              apizza-statService
            uri:
              lb://apizza-statService
            predicates:
              - Path=/apizza-statService/**
            filters:
              - TokenRelay=
              - RemoveRequestHeader=Cookie
          - id:
              apizza-notificationService
            uri:
              lb://apizza-notificationService
            predicates:
              - Path=/apizza-notificationService/**
            filters:
              - TokenRelay=
              - RemoveRequestHeader=Cookie
  security:
    oauth2:
      client:
        registration:
          gateway:
            provider: spring
            client-id: gateway
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - openid
              - resource.read
        provider:
          spring:
            issuer-uri: http://localhost:9000
